### ISSUE TITLE
mxgraph 3.7.3 fails to install using npm

### ISSUE THREAD

**Issue by daddyman** [jgraph/mxgraph#83] opened 2017-06-27 16:08 UTC
npm install of mxgraph 3.7.3 fails during 'grunt build' in the postinstall. The error output is shown below.

The problem is that in the 3.7.3 release the javascript shipped under `javascript/src/js` is one big mxClient.js file instead of the individual files used in previous releases. The postinstall script runs `grunt build` which loads Gruntfile.js and tries to merge all of the javascript files into one file (dist/build.js) with a factory function to load it and export it . Line 14 of Gruntfile.js looks for the mxClient.include pattern in `javascript/src/js/mxClient.js` but doesn't find any and then tries to call `map` on `undefined` because the regular expression does not match anything.

My workaround for now is to stick with version 3.7.2-2 as my code relies on the factory that the grunt build wraps around the mxgraph javscript.

```
> mxgraph@3.7.3 postinstall c:\dev\mx\mxweb\node_modules\mxgraph
> grunt build

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'map' of null
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\
fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":
"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! mxgraph@3.7.3 postinstall: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the mxgraph@3.7.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by tweet** [comment] 2017-06-30 09:38
The same problem in version 3.7.4, when will it be fixed?
Another error is
 `require(parentFolderName === "node_modules" ? "load-grunt-parent-tasks" : "load-grunt-tasks")(grunt)`
this need add 2nd parameter for scope.

**Comment by davidjgraph** [comment] 2017-06-30 09:43
It'll be fixed when someone submits a PR to fix it :)

**Comment by tweet** [comment] 2017-06-30 10:58
@davidjgraph, thanks for your quick reply.

To change the mxClient.js code more modular, we need get all the needed variables to can be exported (like ES6 module import/export). 

We can use the files name as module name before version 3.7.2, but now all the codes turned into one file, it is hard for program to recognise how many and which variables are needed to be exported.

I suggest you give or maintain a list for those first level variables who may be needed for using in the outer.
Then these mxClient.js can be transfer to JS module after exec the script `npm install --save mxgraph`

**Comment by hjzheng** [comment] 2017-07-06 02:08
I have a another problem about npm install 
```
> mxgraph@3.7.1 postinstall /Users/hjzheng/shuyunWorkplace/alidw-fe/node_modules/mxgraph
> grunt build

Running "copy:main" (copy) task
Copied 141 files

Running "concat:dist" (concat) task

Running "webpack:examples" (webpack) task
Warning: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "javascript/examples/webpack/dist" is not an absolute path! Use --force to continue.

Aborted due to warnings.

```

**Comment by NicCOConnor** [comment] 2017-08-08 13:21
@davidjgraph I would like to start putting together a pull request to fix this issue. I have a few questions in order to get started. I don't see the necessary files in either this repo or the Javascript repo to build the npm package. Files such as `package.json, Gruntfile, etc..` I was thinking the best place to put these would be inside the javascript folder. thoughts? or is there another repo that I can submit a PR for. 

Additionally, as mentioned above, in the npm package the mxGraph library has been changed to a single minimized file which breaks the factory object you previously built to export all the classes. Was this done in error or was there a reason.  I don't see the previous object __mxOutput in that minimized file.

Thanks for any assistance!

**Comment by NicCOConnor** [comment] 2017-08-08 17:14
workaround created on my fork. 
`npm install --save git+https://github.com/NicCOConnor/mxgraph.git`

this goes back to the old method of compiling from multiple files to create a dist.js file. 

I'll submit a PR once I get some feedback from @davidjgraph on the additional files in the root of the repo.

**Comment by daddyman** [comment] 2017-08-08 21:23
@NicCOConnor I also could not find the files that create the npm distribution. My workaround was to write a node script that downloads the latest from GitHub and performs the same steps as `Gruntfile.js`. I commit the output file to source control and copy this file to node_modules in a `package.json` postinstall step.

I run this whenever I change the tag I want from mxgraph. Since there isn't a package.json file I had to add a `browser` entry in `package.json`:

```
"browser": {
    "mxgraph": "./node_modules/mxgraph/mxgraph.js"
},
```
`mx/install.js:`
```
const path = require('path');
const fs = require('fs');
const rimraf = require('rimraf');
const { spawn } = require('child_process');

(function () {

    function install() {
        const tag = 'v3.7.4';
        const uri = 'https://github.com/jgraph/mxgraph.git';

        const workdir = path.join(__dirname, 'work');
        const distdir = path.join(__dirname, 'dist');

        return new Promise((resolve, reject) => {
            removedir(distdir)
                .then(() => {
                    return removedir(workdir);
                })
                .then(() => {
                    return clone(uri, tag, workdir);
                })
                .then(() => {
                    return fixup(workdir, distdir);
                })
                .then(() => {
                    resolve();
                })
        });
    }

    function removedir(workdir) {
        return new Promise((resolve, reject) => {
            console.log(`...removing: [${workdir}]`);
            rimraf(workdir, () => {
                resolve();
            });
        });
    }

    function clone(uri, tag, workdir) {
        return new Promise((resolve, reject) => {
            console.log(`...clone from ${uri}: (${tag}): to ${workdir}`);
            const args = ['clone'];
            if (tag) {
                args.push('-b');
                args.push(tag);
            }
            args.push(uri);
            args.push(workdir);
            const child = spawn('git', args);
            child.stdout.setEncoding('utf8');
            child.stderr.setEncoding('utf8');

            child.stdout.on('data', (chunk) => {
                process.stdout.write(chunk);
            });
            child.stderr.on('data', (chunk) => {
                process.stderr.write(chunk);
            });
            child.on('close', (code) => {
                resolve();
            });
        });
    }

    function fixup(srcdir, distdir) {
        const dist_header = '(function (root, factory) {\n' +
            "if (typeof define === 'function' && define.amd) {\n" +
            'define([], factory);\n' +
            "} else if (typeof module === 'object' && module.exports) {\n" +
            'module.exports = factory();\n' +
            '} else {\n' +
            'root.mxgraph = factory();\n' +
            '}\n' +
            '}(this, function () {\n' +
            'return function (opts) {\n' +
            // Opts will be passed into this function, expand them out as if
            // they were globals so they can get picked up by the logic in
            // mxClient.js.
            'for (var name in opts) { this[name] = opts[name]; }\n' +
            'var __mxOutput = {};\n';
        const dist_footer = 'return __mxOutput;\n' +
            '};\n' +
            '}));';

        return new Promise((resolve, reject) => {
            console.log(`...fixup from ${srcdir} to ${distdir}`);

            const basedir = path.join(srcdir, './javascript/src');

            //Find all of the includes in mxClient.js
            const mxClientContent = fs.readFileSync(path.join(basedir, './js/mxClient.js'), 'utf8');
            let deps = mxClientContent.match(/mxClient\.include\([^"']+["'](.*?)["']/gi).map((str) => {
                return "." + str.match(/mxClient\.include\([^"']+["'](.*?)["']/)[1];
            });
            deps = ["./js/mxClient.js"].concat(deps.slice(0));

            let stripIncludeForFile = true; //strip includes from first client (mxClient.js)
            let content = dist_header;
            for (const file of deps) {
                console.log(file);

                //Add the file data
                const fileData = fs.readFileSync(path.join(basedir, file), 'utf8');
                if (stripIncludeForFile) {
                    content += fixString(stripIncludes(fileData));
                    stripIncludeForFile = false;
                } else {
                    content += fixString(fileData);
                }

                //Add export for the file after the data
                const exportName = path.basename(file, '.js');
                const moduleName = path.basename(file, '.js');
                content += makeExport(exportName, moduleName);

                //Extra exports needed from some files
                if (exportName === 'mxHierarchicalLayout') {
                    content += makeExport('mxHierarchicalEdgeStyle', 'mxHierarchicalEdgeStyle');
                }
            }
            content += dist_footer;

            //Write the output
            fs.mkdirSync(distdir);
            const destpath = path.join(distdir, 'mxgraph.js');
            fs.writeFileSync(destpath, content);

            //Done
            resolve();
        })
    }

    function makeExport(exportName, moduleName) {
        return `\n__mxOutput.${exportName} = typeof ${moduleName} !== 'undefined' ? ${moduleName} : undefined;\n`;
    }

    function fixString(data) {
        return data.replace(/[\r]/g, '');   //Remove carriage returns
    }

    function stripIncludes(data) {
        //In mxClient.js remove the include data from the end of the file.
        const index = data.indexOf('PREPROCESSOR-REMOVE-START');
        if (index !== -1) {
            return data.substring(0, index);
        }
        return data;
    }

    //Run
    install()
        .then(() => {
            console.log('complete');
            process.exit(0);
        })
        .catch((err) => {
            console.log(`... failed: ${err}`);
            process.exit(1);
        });
})();
```

**Comment by NicCOConnor** [comment] 2017-08-08 22:11
phew, that looks intense. I'm not sure if you can compare my forked changes, but essentially what I did was 
1. Fork the repo
2. copy the `Gruntfile.js` and `package.json` from the existing npm package (3.7.4)
3. install the npm package directly from git based off my forked repo `npm install --save git+https://github.com/NicCOConnor/mxgraph.git`

it's not the most elegant but it gets me back to where I was with 3.7.2-2

Eventually, I'd like to turn these into proper Typescript / node modules for better Angular consumption, or even Angular components. but I'm not there yet, with regard to the javascript ecosystem.

**Comment by daddyman** [comment] 2017-08-09 01:31
My goal was to be able to use the newer mxgraph versions after 3.7.2-2 and to be able to use newer versions of npm (e.g. 5.3.0). I wanted to avoid grunt because of the issues that were reported with some of the grunt plugins when using newer versions of npm.

**Comment by arseneoaa** [comment] 2017-08-15 08:11
@NicCOConnor Thanks a lot for your fork !

**Comment by PMudra** [comment] 2017-08-31 12:17
Unfortunately, `npm install mxgraph` is still not working using version 3.7.5 😢 
I get the same error as the original reporter.

**Comment by hjzheng** [comment] 2017-09-01 01:46
@PMudra yes，It is still not working. 😞

**Comment by nigel-daniels** [comment] 2017-09-07 21:53
This error applies to 3.7.5 too.

**Comment by sbdevw** [comment] 2017-09-15 14:39
@NicCOConnor  thanks for your fork. 
However I am getting issue while installing form your forked even after using the admin privilege in windows console.
Error: EPERM: operation not permitted, unlink '***\node_modules\fsevents\nod
e_modules\ansi-regex\package.json' 

Pls advise if I am missing anything in my setup ..
Thanks again for your help...

**Comment by NicCOConnor** [comment] 2017-09-15 14:49
Try downgrading npm to 5.3 looks like there's an issue with 5.4 on windows. https://github.com/npm/npm/issues/18380

the fork builds successfully with npm 5.4.2 on OSX

**Comment by sbdevw** [comment] 2017-09-15 19:03
Thanks @NicCOConnor downgrading npm to 5.3 worked !!

**Comment by truthaman** [comment] 2017-09-19 23:59
Can't install on Linux - tried npm 5.3 and 5.4.2, same error as originally reported.

**Comment by rbuckland** [comment] 2017-10-11 07:19
Node Version 8.6.0 (default npm bundled as 5.3.0) on ubuntu works if you use @NicCOConnor 's fork.

```
FROM ubuntu:17.10

ENV DEBIAN_FRONTEND=noninteractive
#
# We are basing off of ubuntu because we want to install servo
#
#
#
# includes npm 5.3.0 which is what we want
ENV NODE_VERSION=v8.6.0

RUN apt-get update && apt-get install -y curl
RUN curl -o /tmp/node.tar.xz https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz
RUN apt-get install -y zutils
RUN cd /usr && tar xJvf /tmp/node.tar.xz --strip 1

# https://github.com/jgraph/mxgraph/issues/83
# specifically a pain.

RUN apt-get install -y git

#
# This fails 
# RUN npm install mxgraph
#  This fails
# RUN npm install --save git+https://github.com/jgraph/mxgraph.git

# This works
RUN npm install --save git+https://github.com/NicCOConnor/mxgraph.git
```

**Comment by jayantmishra** [comment] 2017-10-17 18:39
Thanks @NicCOConnor  , installing the npm package directly from git based off repo npm install --save git+https://github.com/NicCOConnor/mxgraph.git works

**Comment by haycco** [comment] 2017-10-18 06:38
This error applies to 3.7.5 too. !!!!!!!!!! help.

**Comment by bbottema** [comment] 2017-10-20 09:46
Still broken in nodejs 4.4.7 and 6.11.4, npm 5.5.1 (and some older version I don't remember). Sad!

**Comment by bbottema** [comment] 2017-10-20 09:46
Still broken in nodejs 4.7.0 and 6.11.4, npm 5.5.1 (and some older version I don't remember). Sad!

**Comment by davidjgraph** [comment] 2017-12-08 16:48
This doesn't seem to fix the issue. We'll rehire the contractor who implemented the original NPM. As background, you probably noticed that we don't use NPM, nor understand its workings :).

**Comment by hdev0301** [comment] 2017-12-08 17:57
It works fine with npm 5.5.1 on mac.

**Comment by davidjgraph** [comment] 2017-12-08 17:59
@NicCOConnor Can you be persuaded on a contract to look after the NPM side of mxGraph? I'm much rather do that than shift through the endless garage of Upwork contractors...

**Comment by NicCOConnor** [comment] 2017-12-08 18:03
@davidjgraph I'll have to check with my employer. I can contribute to open source projects but moonlighting (getting paid) may be a conflict of interest.

**Comment by hdev0301** [comment] 2017-12-08 18:10
I am working on Upwork.

**Comment by davidjgraph** [comment] 2017-12-08 18:14
@NicCOConnor You can always contribute the fix to the master then win the competition we run straight afterwards for an amount of amazon vouchers that bears a close correlation to the number of hours it took you ;)

@hdev0301 OK, but you can't repeat it ;)

**Comment by hdev0301** [comment] 2017-12-08 18:18
I will be contributing my own solutions to the repo.

**Comment by davidjgraph** [comment] 2017-12-08 18:19
Yeah, I'm kidding, you're more than welcome to have a try. Can you apply?

**Comment by hdev0301** [comment] 2017-12-08 18:21
Yeah, I applied to your job already.

**Comment by hdev0301** [comment] 2017-12-08 18:25
Approve my proposal on Upwork with the name of Alon Yosef.

**Comment by witty3235** [comment] 2017-12-08 18:28
I had a chance to look into the issue.

@daddyman mentioned that "The problem is that in the 3.7.3 release the javascript shipped under javascript/src/js is one big mxClient.js file instead of the individual files used in previous releases. The postinstall script runs grunt build which loads Gruntfile.js and tries to merge all of the javascript files into one file (dist/build.js) with a factory function to load it and export it . Line 14 of Gruntfile.js looks for the mxClient.include pattern in javascript/src/js/mxClient.js but doesn't find any and then tries to call map on undefined because the regular expression does not match anything.".

The tarballs published on npm registry seems to have different structure from the source of git repo.
tarball has one single merged js file under /javascript/src/js, whereas the git contains separated files and folders under /javascript/js folder.

Possible solution:
 - Replacing all the tarballs to contain exactly same structure with the git source under /javascript/src/js folder.
 - Adding single line of validation code to gruntfile.js line 14.

**Comment by davidjgraph** [comment] 2017-12-08 18:34
OK, you can now direct your requests at @hdev0301 8-)

**Comment by davidjgraph** [comment] 2017-12-08 18:43
Actually, I'm not really sure why the master repo isn't public, I can't find anything secret there...

**Comment by hdev0301** [comment] 2017-12-08 18:44
But the access is denied.

**Comment by davidjgraph** [comment] 2017-12-13 15:08
We've made the dev repo public, it's at https://bitbucket.org/jgraph/mxgraph2.

In [/etc/build](https://bitbucket.org/jgraph/mxgraph2/src/2b1559026634a81a53feda6a5a8e6b7f42f423e7/etc/build/?at=master) there's the source Gruntfile.js, mxgraph-package.json, which becomes the package.json and the deploy script, deploy.sh, that we run when everything is building correctly.

[Line 39](https://bitbucket.org/jgraph/mxgraph2/src/2b1559026634a81a53feda6a5a8e6b7f42f423e7/etc/build/deploy.sh?at=master&fileviewer=file-view-default#deploy.sh-39) is where we publish to NPM. So the task (with Alon currently) is to work out how to change the Gruntfile in Bitbucket and then push both files to the correct locations.

**Comment by davidjgraph** [comment] 2017-12-14 13:56
Does the current version here in Github work correctly?

**Comment by NicCOConnor** [comment] 2017-12-14 15:24
@davidjgraph it works with a source install from github `npm install git+https://github.com/jgraph/mxgraph.git --save` although some people have reported issues on windows systems, which I haven't had the time to test. But Linux and OSX are working as expected.

**Comment by davidjgraph** [comment] 2017-12-14 15:35
Nice, thanks for the fixes. I'll close, if you have problems on windows please open a new ticket (and start working with a proper OS ;) )

**Closed by davidjgraph** 2017-12-14 15:35 UTC

**Comment by JaniceLian** [comment] 2017-12-18 10:13
the same error, try the solution above， not work with mxgraph@3.8.0

**Comment by lgleim** [comment] 2018-01-19 14:50
This error is still not solved. I encounter it with both npm 5.3 and 5.6.5 on linux. The issue appears to be grunt related. The current build system appears more then broken. I am counting just about 10 forks in the last few weeks that try to solve this issue and modernize the codebase.
@davidjgraph Do you have a roadmap for the future of mxgraph?  i.e. modernizing code base, migrating to a modern build system, transpilation, typings/Typescript, JSDoc/EsDoc instead of current documentation format?
Do you need to maintain backwardscompatibility with global scoped variables our wouldn't it be time for mxGraph 4.0 with a modern import/export syntax?

**Comment by davidjgraph** [comment] 2018-01-19 15:05
Our key is keeping mxGraph stable so we don't end up with a draw.io re-write to support all these changes.

We have none of those things on the roadmap (we don't have a roadmap) and the community needs to self-organise and implement themselves if these things are such an issue, we not going to do this. This is the whole point of open source :).

**Comment by davidjgraph** [comment] 2018-01-19 15:52
Does 3.9 work?

**Comment by davidjgraph** [comment] 2018-01-20 14:10
I just cloned this repo, performed "npm install" in the root on a mac. The output reports success, so I assume that works. Do these step fail on Linux or were your steps different?

**Comment by NicCOConnor** [comment] 2018-01-20 17:05
So I spent some time on this recently. That method works. Doing a direct grunt build works. When it’s nested in another application’s package.json it has issues finding the npm grunt dependencies, almost as if the postinstall task is run before dependency’s are satisfied. It’s a weird and maddening bug, that had me stumped for a day with no resolution. I think the way forward may be to remove the postinstall grunt build process and just provide a dist.js. I have a need for this now so I may have a pull request on bitbucket soonish

Nic

**Comment by davidjgraph** [comment] 2018-01-20 18:05
There was an error with the deploy step from BB, fixed with https://bitbucket.org/jgraph/mxgraph2/commits/c9df1b8225ce59010b0ae65b95d385f6d8efb7a7. The directory didn't get created so the Github release didn't the grunt file in etc/build originally.

I don't know the mechanics of npmjs, whether a copy is made at publish time, etc. Maybe I'll try having the gruntfile in both the root and etc/build and see if that works.
