### ISSUE TITLE
Offset in mouse selections when page is scrolled down

### ISSUE THREAD

**Issue by angrykoala** [jgraph/mxgraph#58] opened 2017-02-28 15:17 UTC
Apparently, any scroll in a page causes an offset for mouse events in the graph, making nearly impossible to use (in particular, creating new connections) when scrolled down the page. I was able to reproduce this behaviour in the example [Helloport](https://jgraph.github.io/mxgraph/javascript/examples/helloport.html) when making the browser window small enough to allow scrolling:

![image](https://cloud.githubusercontent.com/assets/5960567/23410927/c609fc7a-fdc8-11e6-9d8f-8986acbfda46.png)
_Offset in mouse events problem when page is scrolled_

![image](https://cloud.githubusercontent.com/assets/5960567/23410942/cf31d7aa-fdc8-11e6-9bf8-083d9f997635.png)
_Working correctly when scroll is at the top of the page_

I found this problem in Google Chrome and Firefox.

Moving and resizing components seems to be working fine.

**Comment by alderg** [comment] 2017-02-28 15:29
Duplicate of https://desk.draw.io/helpdesk/tickets/3257

**Comment by alderg** [comment] 2017-03-01 10:55
Thanks for the report, this will be fixed in the next release.

**Closed by alderg** 2017-03-01 10:55 UTC

**Comment by EdwinThivyaraj** [comment] 2017-03-07 14:24
Hi @alderg Is this issue got fixed ? I am currently using 3.7.0.1 version.

**Comment by alderg** [comment] 2017-03-07 14:26
yes, fixed in 3.7.1

**Comment by EdwinThivyaraj** [comment] 2017-03-07 14:31
Thank You @alderg

**Comment by joulestaa** [comment] 2017-03-23 13:35
this problem is still alive.

**Comment by davidjgraph** [comment] 2017-03-23 13:49
@joulestaa Have you tried this [helloport](https://jgraph.github.io/mxgraph/javascript/examples/helloport.html) example? If yes and it fails, which browser/browser version are you using? Are you sure you are looking at the latest (cleared cache)?

**Comment by joulestaa** [comment] 2017-03-23 14:09
helloport is working but whan i use graph with page which has scroll problem appears like 
![mxgraph](https://cloud.githubusercontent.com/assets/7470639/24251509/70afeb60-0feb-11e7-9ce2-50423b5b8ea1.png)

**Comment by davidjgraph** [comment] 2017-03-23 14:10
Can you repost a simple, complete reproduction example?

**Comment by angrykoala** [comment] 2017-03-23 14:12
I found the problem to keep happening in a specific case, but I haven't been able to reproduce in a simple example yet

**Comment by davidjgraph** [comment] 2017-03-23 14:16
@angrykoala does this happen in all browsers? Post a video of it in your app, maybe we can log some numbers to debug it.

**Comment by joulestaa** [comment] 2017-03-23 14:46
If i changed window scroll , drag drop event of an edge or toolbar items appears under my cursor and add that position

**Comment by joulestaa** [comment] 2017-03-23 14:47
how can i fix this problem ? reset all mouse events or what?

**Comment by davidjgraph** [comment] 2017-03-23 14:53
Fix what problem? I don't see a clear problem description

**Comment by joulestaa** [comment] 2017-03-23 15:02
I will explain in detail. When I down the page with scroll bar, to combine the cells in graph with edge, the edge appears to be under than the merge field down. I posted this photo at previous post

**Comment by nlinnett** [comment] 2017-03-23 15:08
Joulestaa, I had a very similar problem when I started with my application.
It turned out to be a bug in the specific version of the library I was
using (I was using 3.7.0.1).

As soon as I updated to 3.7.1 the problem went away.

Nigel

**Comment by joulestaa** [comment] 2017-03-23 15:12
I already use the latest version. I will open a new window in the same way as the graph examples at full height.
Thanks a lot.

**Comment by angrykoala** [comment] 2017-03-23 15:36
@davidjgraph Sorry, I cannot send a video/screenshot of the application at the moment. However, the problem is exactly the described in this issue, but only under certain conditions instead of always (Sorry, I couldn't figure out the exact conditions that trigger the problem). In my app (running on a Chrome browser) one graph behaves properly, while another graph in other page is misbehaving. Both (obviously) are running the same version (after the fix) of mxGraph, and basically the same browser and web.

Before the fix, both graphs were misbehaving, so the main issue (the one I could reproduce with helloport) is fixed, but in unknown conditions it is still happening

**Comment by alderg** [comment] 2017-04-08 13:43
Can you please provide a test case to reproduce this issue?

**Comment by jchiellini** [comment] 2017-08-07 22:22
Has anything transpired with this issue? I am experiencing this exact behavior described in the top post. The outer div has an 'overflow: auto' and dragging appears to be fine as long as the scroll is at the top of the page. When scrolling down, an offset in mouse position causes issues when moving edges or dragging symbols onto the graph. 

Using mxgraph version 3.7.4, javascript in a google chrome browser.

**Comment by alderg** [comment] 2017-08-08 06:44
Can you check if this fix for mxUtils.getScrollOrigin fixes it: https://groups.google.com/d/msg/drawio/vtRndSnOKrM/wcvwVA_-BwAJ

**Comment by jchiellini** [comment] 2017-08-08 12:40
Yes, Hallelujah! This was such a big concern for me. Thank you for responding so quickly with a viable solution @alderg
