### ISSUE TITLE
this.graph.setCellStyles(mxConstants.STYLE_SHADOW,false);Error

### ISSUE THREAD

**Issue by WanManito** [jgraph/mxgraph#407] opened 2019-12-04 01:19 UTC
![image](https://user-images.githubusercontent.com/26118508/70103734-f1fc0980-1676-11ea-9582-94d46db2a365.png)
Set a Boolean value, but print is of type string

**Comment by davidjgraph** [comment] 2019-12-04 17:09
Your question is seeking debugging help but needs more information. The question should be updated to include desired behavior, a specific problem or error, and the shortest code necessary to reproduce the problem.

**Comment by WanManito** [comment] 2019-12-05 00:50
Title is the shortest code to reproduce the problem. I want to control the shadow Settings and find that only Boolean values take effect,But when I write a Boolean value through graph.setcellstyles (key,value), its properties become strings,String type doesn't work for it, and I can basically set all the other properties in this way.

**Comment by davidjgraph** [comment] 2019-12-05 09:44
I just tested this it works for me. Since you haven't provided an exact reproduction case or environment details I'm closing.

**Closed by davidjgraph** 2019-12-05 09:44 UTC
