### ISSUE TITLE
 How to change the style of my edge?

### ISSUE THREAD

**Issue by yschuenck** [jgraph/mxgraph#245] opened 2018-08-28 20:02 UTC
I need to create an edge in this format, but I do not know how to change the arrow style.

![image](https://user-images.githubusercontent.com/9735292/44747183-f08e7980-aae2-11e8-99c2-6c06b5db83d7.png)

My edge

![image](https://user-images.githubusercontent.com/9735292/44747365-64308680-aae3-11e8-8004-c01a4eabf5f7.png)

**Comment by alderg** [comment] 2018-08-29 04:15
Duplicate of https://desk.draw.io/helpdesk/tickets/8755

**Closed by alderg** 2018-08-29 04:15 UTC

**Comment by yschuenck** [comment] 2018-09-04 02:14
https://stackoverflow.com/q/52068671/10286700
